site:
  title: New OSDev Wiki
  url: https://osdev.wiki
  start_page: wiki::index.adoc
content:
  sources:
  - url: ./
ui:
  bundle:
    url: https://nightly.link/samjakob/osdev-wiki-ui/workflows/bundle-ui/master/osdev-wiki-ui.zip
    snapshot: true

